from build_random_graph import Builder
from field import Field
import sys

class Interface: 
	field = []
	def buildRandomMazeWithDsu(self, n, m): 
		bld = Builder()
		self.field = bld.buildRandomMazeWithDsu(n, m)

	def buildRandomMazeWithDfs(self, n, m): 
		bld = Builder()
		self.field = bld.buildRandomMazeWithDfs(n, m)

	def setStart(self, xx, yy): 
		self.field.setStart(xx, yy)

	def setFinish(self, xx, yy): 
		self.field.setFinish(xx, yy)

	def buildPath(self): 
		self.field.buildPath()

	def printField(self): 
		ms = self.field.showField()
		for x in ms: 
			print(*x, sep = '')

	def download(self, file_name): 
		f1 = open(file_name, 'r')
		n, m = map(int, f1.readline().split())
		edges = []
		cnt_edges = n * m - 1
		for i in range(cnt_edges): 
			e1, e2 = map(int, f1.readline().split())
			edges.append([e1, e2])
		print(edges)
		bld = Builder()
		bld.maze.n = n
		bld.maze.m = m
		bld.maze = Field(n, m)		
		self.field = bld.buildMaze(edges)
		f1.close()

	def upload(self, file_name): 
		self.field.setStart(-1, -1)
		self.field.setFinish(-1, -1)
		self.field.path = []
		maze = self.field.getString();
		f1 = open(file_name, "w+")
		f1.write("SIZE\n")
		f1.write(str(self.field.n) + " " + str(self.field.m) + '\n')
		f1.write("EDGES\n")
		for x in self.field.edges: 
			f1.write(str(x[0]) + " " + str(x[1]) + '\n')
		f1.write("MAZE\n")
		f1.write(maze)

		f1.close()

print("Hello, let's start the game!")
print()
print("There are 3 games you can choose. Print the number")
print("1) Random maze generated by dsu")
print("2) Random maze generated by dfs")
print("3) Do you wanna upload your own maze?")
type_game = int(input())
game = Interface()

if type_game <= 2:
	print("Please, enter the size of the maze")
	n, m = map(int, input().split())		
	if game == 1:		
		game.buildRandomMazeWithDsu(n, m)
	else: 
		game.buildRandomMazeWithDfs(n, m)
else: 
	print("here")
	game.download("maze.txt")

print("That's what happened")
game.printField()
print("Left to set the start!")
n, m = map(int, input().split())
n -= 1 
m -= 1 
game.setStart(n, m)
print("This is last, I promise. Set the finish!")
n, m = map(int, input().split())
n -= 1
m -= 1
game.setFinish(n, m)
game.printField()
print("Try to solve it!")
print("Enter 'y' if you solved the maze or want to see the answer") 
s = input()
game.buildPath()
game.printField()
print("Do you wanna download this maze? Print 'y' or 'n'")
s = input()
if s == 'y':
	#загрузить файл	
	game.upload("maze.txt")
	print("I have just upload this maze to file maze.txt")
	
print("bye bye:)\nthanks for playing")
